[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd server && npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd client && NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5000} npm run build"
]

[start]
cmd = "cd server && npm start"
